#!/usr/bin/env bash
#
# Upload the converted Roman-Urdu GGML models to HuggingFace.
#
# Walks you through: (1) generating an HF Write access token, then uses it to
# (2) create the public model repo and (3) upload both .bin files as Git LFS.
# The token is captured in .env as HF_TOKEN for future re-runs.
#
# Generated by the /wizard skill.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

VENV_PY="${VENV_PY:-/home/femustafa/projects/learning_ws/tools/validate_stt/.venv/bin/python}"
# Default location of the freshly-converted GGML models (ticket 16 output).
F16_MODEL="${F16_MODEL:-/var/tmp/roman-urdu/out/ggml-model-f16.bin}"
Q40_MODEL="${Q40_MODEL:-/var/tmp/roman-urdu/out/ggml-model-q4_0.bin}"
REPO="${REPO:-femustafa/voicedictation-models}"

TOTAL_STAGES=3

banner "Upload Roman-Urdu GGML to HuggingFace"

# ── Stage 1: HF access token ──────────────────────────────────────────────
stage "HuggingFace: access token"
say "The upload needs a Write access token from your HuggingFace account."
say "If you don't have an account, sign up first — it takes a minute."
open_url "https://huggingface.co/join"
pause "Create/sign in to your account (or cancel if it's already open), then press Enter."
step "Open the Access Tokens page."
open_url "https://huggingface.co/settings/tokens"
step "Click 'Create new token' → name it 'voicedictation-upload' → Role: Write → Create."
step "Copy the token that appears (it starts with hf_ and is shown only once)."
ask_secret HF_TOKEN "Paste your HuggingFace Write token:"
if [[ "$HF_TOKEN" != hf_* ]]; then
  warn "That doesn't start with 'hf_' — double-check you pasted the full token."
  confirm "Continue anyway?" || pause "Press Enter to re-read the instructions above."
fi
write_env HF_TOKEN "$HF_TOKEN"

# ── Stage 2: create the public repo ───────────────────────────────────────
stage "Create public model repo"
say "Now I'll create the public repo '$REPO' and ensure .bin files are stored"
say "as Git LFS. This runs against the HuggingFace API using your token."
if REPO_RESULT=$("$VENV_PY" - "$REPO" "$HF_TOKEN" <<'PY'
import sys
from huggingface_hub import HfApi
repo, token = sys.argv[1], sys.argv[2]
api = HfApi(token=token)
who = api.whoami()
username = who["name"]
if not repo.startswith(username + "/"):
    repo = f"{username}/voicedictation-models"
api.create_repo(repo_id=repo, private=False, visibility="public", repo_type="model", exist_ok=True)
print(repo)
PY
) && [[ "$REPO_RESULT" =~ ^[A-Za-z0-9_-]+/ ]]; then
  REPO="$REPO_RESULT"
  write_env HF_REPO "$REPO"
  note "Repo ready: https://huggingface.co/$REPO"
else
  warn "Could not create/verify repo. Common causes: token lacks write scope, or repo name taken."
  confirm "Open the repo-create page in your browser to do it manually?" && {
    open_url "https://huggingface.co/new"
    say "Set Owner to your account, Name to 'voicedictation-models', Type: Model, Visibility: Public."
    pause "Press Enter once the repo is created."
  }
  confirm "Try the programmatic upload anyway (requires the repo to exist)?" || exit 1
fi

# ── Stage 3: upload both GGML files ───────────────────────────────────────
stage "Upload GGML files (f16 + q4_0)"
say "Uploading the two converted model files to '$REPO' as Git LFS."
note "Sources:"
note "  f16: $F16_MODEL"
note "  q4_0: $Q40_MODEL"
for f in "$F16_MODEL" "$Q40_MODEL"; do
  [[ -s "$f" ]] || { warn "missing file: $f (did ticket 16's conversion run?)"; }
done
confirm "Upload both .bin files to HF now?" || exit 1
if "$VENV_PY" - "$REPO" "$HF_TOKEN" "$F16_MODEL" "$Q40_MODEL" <<'PY'
import sys
from huggingface_hub import HfApi, upload_file
repo, token, f16, q40 = sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4]
api = HfApi(token=token)
for local_path, name in ((f16, "ggml-model-f16.bin"), (q40, "ggml-model-q4_0.bin")):
    print(f"uploading {name} ({__import__('os').path.getsize(local_path)} bytes)...")
    upload_file(path_or_fileobj=local_path, path_in_repo=name,
                repo_id=repo, repo_type="model", token=token)
    print("done:", name)
PY
then
  note "Both files uploaded."
else
  warn "Upload failed. Check the error above (network, token scope, or repo visibility)."
fi

# ── Closing ───────────────────────────────────────────────────────────────
finish
say "Public files (verify these return HTTP 200):"
say "  https://huggingface.co/$REPO/resolve/main/ggml-model-q4_0.bin"
say "  https://huggingface.co/$REPO/resolve/main/ggml-model-f16.bin"
